name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: 'maven'

    - name: Make Maven wrapper executable
      run: chmod +x ./mvnw

    - name: Build with Maven
      run: ./mvnw clean install

    - name: Run tests
      run: ./mvnw test

    - name: Build Docker image
      run: docker build -t demo:${{ github.sha }} .

    - name: Save Docker image
      run: docker save demo:${{ github.sha }} > demo-image.tar

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: demo-docker-image
        path: demo-image.tar
        retention-days: 7

  kubernetes-validation:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Minikube
      uses: medyagh/setup-minikube@latest
      with:
        minikube-version: latest
        kubernetes-version: v1.28.0

    - name: Download Docker image artifact
      uses: actions/download-artifact@v4
      with:
        name: demo-docker-image

    - name: Load Docker image to Minikube
      run: |
        eval $(minikube docker-env)
        docker load < demo-image.tar
        docker tag demo:${{ github.sha }} demo:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Wait for deployment
      run: |
        kubectl wait --for=condition=ready pod -l app=demo --timeout=300s || true
        kubectl get pods
        kubectl get services

    - name: Show deployment status
      if: always()
      run: |
        echo "=== Pods ==="
        kubectl get pods
        echo "=== Services ==="
        kubectl get services
        echo "=== Deployment Details ==="
        kubectl describe deployment demo-app
        echo "=== Pod Logs ==="
        kubectl logs -l app=demo --tail=50 || echo "No logs available"

    - name: Verify service accessibility
      run: |
        # Get the service URL
        SERVICE_URL=$(minikube service demo-service --url)
        echo "Service URL: $SERVICE_URL"

        # Wait a bit for the service to be fully ready
        sleep 10

        # Test the actuator health endpoint
        echo "Testing /actuator/health endpoint..."
        HTTP_CODE=$(curl -f -s -o /dev/null -w "%{http_code}" $SERVICE_URL/actuator/health || echo "000")
        echo "Health check returned: $HTTP_CODE"

        if [ "$HTTP_CODE" = "200" ]; then
          echo "✅ Health check passed!"
        else
          echo "❌ Health check failed with code: $HTTP_CODE"
          exit 1
        fi

        # Get detailed health response
        echo "Health endpoint response:"
        curl -s $SERVICE_URL/actuator/health | jq '.' || curl -s $SERVICE_URL/actuator/health

  docker-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Hadolint (Dockerfile linter)
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        failure-threshold: warning
